# Generated by Django 4.0.1 on 2022-09-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/real_estate/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_estate_type', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом')], max_length=100, null=True, verbose_name='Вид недвижимости')),
                ('number_of_rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена')),
                ('subject_to_mortgage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подлежание ипотеки')),
                ('primary_secondary', models.CharField(blank=True, choices=[('primary', 'Первичный'), ('secondary', 'Втооричный')], max_length=100, null=True, verbose_name='Первичный/Вторичный')),
                ('year_of_construction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Год постройки')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('presence_balcony', models.BooleanField(default=True, verbose_name='Наличие балкона')),
                ('glazed_balcony', models.CharField(blank=True, choices=[('open', 'Открытый'), ('glazed', 'Застекленный')], max_length=100, null=True, verbose_name='Застекленность балкона')),
                ('number_of_bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество санузлов')),
                ('number_of_square_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество квадратных метров')),
                ('current_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текущее состояние')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('district_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_districts', to='real_estate.citydistricts', verbose_name='Район города')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='real_estate.images', verbose_name='Фото')),
            ],
        ),
    ]
