# Generated by Django 4.0.1 on 2022-09-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydistricts',
            options={'verbose_name': 'Район', 'verbose_name_plural': '02 Районы'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Фото', 'verbose_name_plural': '03 Фотографии недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': '01 Недвижимости'},
        ),
    ]
