# Generated by Django 4.0.1 on 2022-09-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_alter_citydistricts_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='photo',
        ),
        migrations.AddField(
            model_name='images',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_images', to='real_estate.realestate', verbose_name='Фото'),
        ),
    ]
