# Generated by Django 4.0.1 on 2022-09-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_alter_realestate_real_estate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.realestate', verbose_name='Квартира'),
        ),
    ]
