# Generated by Django 4.0.1 on 2022-09-14 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0008_alter_images_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, у которых данная недвиэимость в избарнных'),
        ),
    ]
