# Generated by Django 4.0.1 on 2022-09-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsforcommunication',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': '01 Контакты'},
        ),
    ]
