# Generated by Django 4.0.1 on 2022-09-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.TextField()),
                ('url_link', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news_article/images/')),
                ('ordering_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': '01 Новости',
                'ordering': ['ordering_number'],
            },
        ),
    ]
