# Generated by Django 4.0.1 on 2022-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='descriptions',
            field=models.TextField(verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/news_article/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='ordering_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ordering_number'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='published_date'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='url_link'),
        ),
    ]
