# Generated by Django 4.0.1 on 2022-09-18 14:14

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_newsarticle_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Новость', 'verbose_name_plural': '01 Новости'},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='ordering_number',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='url_link',
        ),
        migrations.CreateModel(
            name='NewsArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.TextField()),
                ('url_link', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news_article/images/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contents.newsarticle')),
            ],
            options={
                'verbose_name': 'Новость Translation',
                'db_table': 'contents_newsarticle_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
