version: "3.7"

services:
  app:
    build: .
    container_name: my_app_consult
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    command: bash -c "python3 manage.py migrate && gunicorn --bind :8080 --workers 4 core.wsgi:application"
    depends_on:
      - db
  db:
    image: postgres:12.6-alpine
    container_name: my_db_consult
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

volumes:
  postgres_data: