# Generated by Django 4.0.1 on 2022-09-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0009_realestate_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='real_estate.realestate', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Отзывы клиентов',
                'verbose_name_plural': '01 Отзывы клиентов',
            },
        ),
    ]
