# Generated by Django 4.0.1 on 2022-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Полное описание услуги')),
                ('order_service', models.CharField(max_length=255, verbose_name='Заказ услуги для обратной связи')),
            ],
        ),
    ]
