# Generated by Django 4.0.1 on 2022-09-08 13:15

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_filled', models.BooleanField(default=False)),
                ('kyc_verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_change', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('phone_verification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_cyrillic', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_cyrillic', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_latin', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_latin', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('iin_number', models.CharField(blank=True, max_length=12, null=True)),
                ('avatar', models.ImageField(default='images/user_pics/default.png', null=True, upload_to='images/user_pics/', verbose_name='Фото пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': '01 Пользователи',
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
    ]
