# Generated by Django 4.0.1 on 2022-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/programs/')),
            ],
            options={
                'verbose_name': 'Программы',
                'verbose_name_plural': '01 Программы',
            },
        ),
    ]
