# Generated by Django 4.0.1 on 2022-09-18 18:04

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='title',
        ),
        migrations.CreateModel(
            name='ProgramsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/programs/')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='programs.programs')),
            ],
            options={
                'verbose_name': 'Программы Translation',
                'db_table': 'programs_programs_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
