# Generated by Django 4.0.1 on 2022-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_programs_descriptions_remove_programs_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstranslation',
            name='descriptions',
            field=models.TextField(verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='programstranslation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/programs/', verbose_name='Логотип программы'),
        ),
        migrations.AlterField(
            model_name='programstranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название программы'),
        ),
    ]
